### ISSUE TITLE
"type" field is automatically set even if vendor defined and type not set in the applied YAML

### ISSUE THREAD

**Issue by ivanzolotuhin** [crossplane-contrib/provider-pagerduty#13]
### What happened?
As per Terraform PagerDuty provider documentation to integrate with a vendor (e.g. Datadog) I should use the "vendor" field instead of "type". But if I am applying this YAML then "type" field added automatically with value = "generic_events_api_inbound_integration" and the error about conflict of "vendor" and "type" fields is displayed in the status.

But the same resource works perfect for generic integrations like APIv2 for Prometheus, where "type" field is required and "vendor" field not.

### How can we reproduce it?
Apply this YAML (this is the correct Datadog Vendor ID):
```
apiVersion: service.pagerduty.crossplane.io/v1alpha1
kind: Integration
metadata:
  labels:
    app: hello-world-dev-datadog
  name: hello-world-dev-datadog
spec:
  forProvider:
    name: Datadog (Managed by Crossplane)
    serviceSelector:
      matchLabels:
        app: hello-world-dev
    vendor: PAM4FGS
  writeConnectionSecretToRef:
    name: hello-world-dev-datadog
    namespace: crossplane-system
```
Tried to set "type: null" with the same result
The result will be (some metadata obfuscated):
```
$ kubectl get integration.service.pagerduty.crossplane.io hello-world-dev-datadog -o yaml
apiVersion: service.pagerduty.crossplane.io/v1alpha1
kind: Integration
metadata:
  finalizers:
  - finalizer.managedresource.crossplane.io
  labels:
    app: hello-world-dev-datadog
  name: hello-world-dev-datadog
spec:
  deletionPolicy: Delete
  forProvider:
    integrationKey: c45aa5875f5a400cc18a8bXXXXXXXX
    name: Datadog (Managed by Crossplane)
    service: PNXXXXX
    serviceRef:
      name: hello-world-dev
    serviceSelector:
      matchLabels:
        app: hello-world-dev
    type: generic_events_api_inbound_integration
    vendor: PAM4FGS
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: hello-world-dev-datadog
    namespace: crossplane-system
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2023-07-18T17:13:02Z"
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-07-18T17:13:36Z"
    message: |-
      observe failed: cannot run refresh: refresh failed: Conflicting configuration arguments: "type": conflicts with vendor
      Conflicting configuration arguments: "vendor": conflicts with type
    reason: ReconcileError
    status: "False"
    type: Synced
  - lastTransitionTime: "2023-07-18T17:13:06Z"
    reason: Finished
    status: "True"
    type: AsyncOperation
  - lastTransitionTime: "2023-07-18T17:13:06Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
```
The result: 
In order to fill the "status.atProvider" I have to manually edit K8S live resource and remove "type" field. Then "status.atProvider" filled and "type" field added immediately back as well.
It actually creates Datadog integration, but status if out-of-sync and in order to delete this resource from K8S I need to manually remove finalizers after deleting the resource and then manually delete the integration from PagerDuty.

### What environment did it happen in?
Crossplane version: v1.10.1
Provider version: v0.3.0
Kubernetes version: AWS EKS v1.27.3-eks-a5565ad
