### ISSUE TITLE
`spec.managementPolicies` is set to a non-default value but the feature is not enabled: [Observe]

### ISSUE THREAD

**Issue by jleni** [crossplane-contrib/provider-pagerduty#33]
Similar issue as https://github.com/crossplane-contrib/provider-pagerduty/issues/28

- Crossplane 0.14.2
- Provider v0.6.1

Installed provider
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-pagerduty
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-pagerduty:v0.6.1
```

(also credentials, etc.)

Then something simple as:
```
apiVersion: user.pagerduty.crossplane.io/v1alpha1
kind: User
metadata:
  name: test
  annotations:
    name: user-test
    crossplane.io/external-name: user-test
spec:
  forProvider: {}
  managementPolicies: ["Observe"]
```

Error message shows:
```
`spec.managementPolicies` is set to a non-default value but the feature is not enabled: [Observe]
```
