### ISSUE TITLE
Provider could not decode JSON response

### ISSUE THREAD

**Issue by tschlaepfer** [crossplane-contrib/provider-pagerduty#66]
Today I tested the provider and found that it seams there is an issue with decoding the response from PagerDuty. Applying the following team
```
apiVersion: team.pagerduty.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
  name: test-team
spec:
  deletionPolicy: Delete
  forProvider:
    description: Product and Engineering
    name: Product Development
```
I get the following error:
```
cannot run refresh: refresh failed: Error reading PagerDuty team : Could not decode JSON response: json: cannot unmarshal array into Go value of type pagerduty.Team
```
I got the same error when trying to create a business service. Can someone have a look a this issue?
